export const SET_QUERY_PARAMS = 'SET_QUERY_PARAMS';
export const SET_FILTERS_PARAMS = 'SET_FILTERS_PARAMS';
export const SET_SORT_ORDER = 'SET_SORT_ORDER';
export const REQUEST_DEFAULT_PRICE = 'REQUEST_DEFAULT_PRICE';
export const REQUESTED_DEFAULT_PRICE_SUCCEEDED = 'REQUESTED_DEFAULT_PRICE_SUCCEEDED';
export const REQUESTED_DEFAULT_PRICE_FAILED = 'REQUESTED_DEFAULT_PRICE_FAILED';
export const SET_ESSENTIAL_QUERY_PARAMS = 'SET_ESSENTIAL_QUERY_PARAMS';
export const SET_DEFAULT_ESSENTIAL_QUERY_PARAMS = 'SET_DEFAULT_ESSENTIAL_QUERY_PARAMS';
