export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const REQUESTED_SEARCH = 'REQUESTED_SEARCH';
export const REQUESTED_SEARCH_SUCCEEDED = 'REQUESTED_SEARCH_SUCCEEDED';
export const REQUESTED_SEARCH_FAILED = 'REQUESTED_SEARCH_FAILED';
export const CLEAR_SEARCH_FIELD = 'CLEAR_SEARCH_FIELD';
export const SET_SEARCH_SORT_ORDER = 'SET_SEARCH_SORT_ORDER';
